// GENERATED FILE - DO NOT MODIFY
// Generated by: Flutter
// Purpose: Localization support

class Messages {
  // English
  static const Map<String, String> en = {
    'app_name': 'Plakyab',
    'search': 'Search',
  };

  // Arabic
  static const Map<String, String> ar = {
    'app_name': 'بلاكيب',
    'search': 'بحث',
  };

  // French
  static const Map<String, String> fr = {
    'app_name': 'Plakyab',
    'search': 'Rechercher',
  };

  // Spanish
  static const Map<String, String> es = {
    'app_name': 'Plakyab',
    'search': 'Buscar',
  };
}
